### ISSUE TITLE
Serialization?

### ISSUE THREAD

**Issue by pawamoy** [tristanlatr/pydocspec#1]
I see that docspec has a `dump_module` function, but it does not understand objects wrapped by pydocspec.

```python
UnionTypeError: type `ObjectType(pydocspec.Data)` is not a member of @union `typing.Union[docspec.Data, docspec.Function, docspec.Class, docspec.Module, docspec.Indirection]`
```

Is there a way to serialize an enhanced pydocspec module?

**Comment by tristanlatr** [comment]
It’s now possible to load and dump pydocspec modules by converting them back to docspec and use the function provided by docspec to dump it, see https://github.com/tristanlatr/pydocspec/blob/aabd3307e06e8100bc86fec74e1168f2d83c83bf/pydocspec/test/__init__.py#L79

**Comment by tristanlatr** [comment]
Exemple:

```python 
        import json
        import docspec
        import pydocspec
        from pydocspec import converter
        root = pydocspec.load_python_modules(...)
        docspec_modules = converter.back_convert_modules(root.root_modules)
        raw_docspec_json = {'modules': []}
        for m in docspec_modules:
            raw_docspec_json['modules'].append(docspec.dump_module(m))
        with open('~/.mysoftware/docspec_modules.json', 'w') as f:
            json.dump(raw_docspec_json, f)
```

**Comment by pawamoy** [comment]
Is any extra metadata (added by pydocspec) lost after serialization?

**Comment by tristanlatr** [comment]
None that the tests can spot at the moment. 

Note that the additional fields are not serialized, but are re computed from the data already present.
