### ISSUE TITLE
Implement C3Linearization with class objects and provide correct inherited_members property

### ISSUE THREAD

**Issue by tristanlatr** [tristanlatr/pydocspec#2]
With the current logic (which not even implemented yet, but I pasted the old version in comments, see https://github.com/tristanlatr/pydocspec/blob/dce733c06ff0384647744065d6881ec0a691950a/pydocspec/__init__.py#L491), methods inherited via more than one class are documented more than once (https://github.com/twisted/pydoctor/issues/10). 

There is a readable implementation of the algorithm, that should be adaptable for class instance: https://github.com/pilosus/c3linear

Let's note that we won't have the complete mro if all objects are not in the system, since we would not be able to resolve them to an `ApiObject`, same with builtins. But it's better than listing methods twice!

I think of the following property for the interface:
```python
class Class:
    class InheritedMember:
        member: ApiObject
        origin: ApiObject
        inherited_via: List[ApiObject]
        parent: Class
    @property
    def inherited_members(self) -> List[InheritedMember]:
        ...
```

Any contribution/feedback regarding that would be appreciated.

**Comment by pawamoy** [comment]
Would it make sense to try and parse the parent classes coming from outside (other packages) to get the complete MRO?

**Comment by tristanlatr** [comment]
Yes. Maybe we could include serialized docspec modules for the default library (and maybe others), this way, we can load this data in the system as well. We should provide a property like ‘is_stdlib’ such that one can filter out those objects when generating the output files.

Don’t think it’s that related to the c3 linearization, though. Having a correct inherited_members property with the objects in the system is the issue. Then we can any custom objects to the system.

I’m working on a better designed version of the converter/object factory. It would work by loading  any « brain » modules available containing sets of mixin classes applicable to ApiObject subclasses and sets of post processors, with a priority of execution. This way, it will be easy to develop custom modules and apply them to the defaults sets of « brain » modules (base, attrs, zope, dataclasses, etc). 

To support resolving inherited functions from other libraries, we need to have those libraries in the system (the root) as well. It’s just a matter if we can resolve all base names to an ApiObject. So, in this perspective, we only need to parse and add external libraries to the system in a custom post processor and it should work.
